name = "AffyCelFiles"
uuid = "efc83544-1c47-49f8-8867-17a7f6cc0942"
authors = ["Oliver Heil <git@heilbit.de>"]
version = "0.1.0"

[deps]
CRC32c = "8bf52ea8-c179-5cab-976a-9e18b702a9bc"

[compat]
julia = "1"

